services:
  - type: web
    name: presentacion-web
    runtime: python
    plan: free
    buildCommand: mkdir -p data static/img && pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: ADMIN_PASSWORD
        value: Multinova202
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true

